/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.User;
import java.awt.Point;
import javax.swing.JFrame;

/**
 *
 * @author Hiruni CH
 */
public class MainUI extends javax.swing.JFrame {
    
    private User user;

    /**
     * Creates new form MainUI
     */
    
    public MainUI(){
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
    }
    
    @SuppressWarnings("deprecation")
    public MainUI(User user) {
        this.user = user;
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        
        System.out.println(user.getId_number() + " " + user.getFirst_name() + " " + user.getUser_type().toString());
       
        
//        btn_history
//                btn_comfirm
//                btn_reserve
//                        btn_getDetails
//                        btn_get_assign_hall
//        

        
       
        txt_userID.setText(user.getId_number());
        
        txt_user.setEditable(false);
        txt_userID.setEditable(false);
       

        switch (user.getUser_type()) {
            case STUDENT:
                 txt_user.setText("Student");
                btn_comfirm.setEnabled(false);
                btn_get_assign_hall.setEnabled(false);
                btn_register_users.hide();
                break;
            case NON_ACADEMIC:
                txt_user.setText("Non Academic");
                btn_comfirm.setEnabled(false);
                btn_history.setEnabled(false);
                btn_reserve.setEnabled(false);
                btn_register_users.hide();
                break;
            case STAFF:
                txt_user.setText("Academic");
                btn_comfirm.setEnabled(false);
                btn_get_assign_hall.setEnabled(false);
                btn_register_users.hide();
                break;
            default:
                txt_user.setText("Admin");
                btn_get_assign_hall.setEnabled(false);
                btn_reserve.setEnabled(false);
                break;
        }
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_comfirm = new javax.swing.JButton();
        btn_reserve = new javax.swing.JButton();
        btn_getDetails = new javax.swing.JButton();
        btn_get_assign_hall = new javax.swing.JButton();
        btn_history = new javax.swing.JButton();
        txt_user = new javax.swing.JTextField();
        txt_userID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_register_users = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_profile = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Welcome to Reservation System");

        btn_comfirm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_comfirm.setText("Comfirm Reservations");
        btn_comfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comfirmActionPerformed(evt);
            }
        });

        btn_reserve.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_reserve.setText("Reserve a Hall");
        btn_reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reserveActionPerformed(evt);
            }
        });

        btn_getDetails.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_getDetails.setText("Get Hall Details");
        btn_getDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getDetailsActionPerformed(evt);
            }
        });

        btn_get_assign_hall.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_get_assign_hall.setText("View Assigned Halls");
        btn_get_assign_hall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_get_assign_hallActionPerformed(evt);
            }
        });

        btn_history.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_history.setText("Reservation History");
        btn_history.setMargin(new java.awt.Insets(3, 14, 2, 14));
        btn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historyActionPerformed(evt);
            }
        });

        txt_user.setBackground(new java.awt.Color(51, 0, 0));
        txt_user.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txt_user.setForeground(java.awt.Color.white);

        txt_userID.setBackground(new java.awt.Color(51, 0, 0));
        txt_userID.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txt_userID.setForeground(java.awt.Color.white);

        jButton1.setBackground(java.awt.Color.red);
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_register_users.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_register_users.setText("Register Users");
        btn_register_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register_usersActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(18, 30, 49));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("User Type  ");

        jLabel3.setBackground(new java.awt.Color(18, 30, 49));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("User ID");

        btn_profile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_profile.setText("Profile ");
        btn_profile.setMargin(new java.awt.Insets(3, 14, 2, 14));
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton1)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_reserve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_comfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_getDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_get_assign_hall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_history, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_register_users, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 131, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_profile))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btn_history))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_comfirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btn_reserve)
                .addGap(18, 18, 18)
                .addComponent(btn_getDetails)
                .addGap(18, 18, 18)
                .addComponent(btn_get_assign_hall)
                .addGap(18, 18, 18)
                .addComponent(btn_register_users)
                .addGap(19, 19, 19))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reserveActionPerformed
        // TODO add your handling code here:
        Reservation obj = new Reservation(user,"NEW");
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_reserveActionPerformed

    private void btn_getDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getDetailsActionPerformed
        // TODO add your handling code here:
        All_rooms obj = new All_rooms(user);
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        obj.setVisible(true);
        
    }//GEN-LAST:event_btn_getDetailsActionPerformed

    private void btn_comfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comfirmActionPerformed
        // TODO add your handling code here:
        Admin_comfirmation obj = new Admin_comfirmation(user);
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_comfirmActionPerformed

    private void btn_get_assign_hallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_get_assign_hallActionPerformed
        // TODO add your handling code here:
        Non_academic obj = new Non_academic(user);
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_get_assign_hallActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
        // TODO add your handling code here:
        History obj = new History(user);
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_historyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_register_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register_usersActionPerformed
        // TODO add your handling code here:
        Registration obj = new Registration(user);
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_register_usersActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
        // TODO add your handling code here:
        Profile obj = new Profile(user);
        obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        obj.setVisible(true);
    }//GEN-LAST:event_btn_profileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_comfirm;
    private javax.swing.JButton btn_getDetails;
    private javax.swing.JButton btn_get_assign_hall;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_register_users;
    private javax.swing.JButton btn_reserve;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_user;
    private javax.swing.JTextField txt_userID;
    // End of variables declaration//GEN-END:variables
}
